// ─────────────────────────────────────────────────────────────────────────────
  // Vendored from duniterum/TheSyndicate main @ cf4ca34c74599de1324e77052f1a81dd15cb1cc0
  // source path: src/lib/contract-registry.ts
  // Read-only canon asset. Do not edit logic.
  // NOTE: This directory is excluded from the api-server TypeScript program and is
  // not yet imported by active app code. It exists as pinned local canon so future
  // status/contracts/proof/archive/token/sale wiring reads real files, not memory.
  // A future wiring slice owns any strict-mode / server-runtime adaptation.
// CONVERSION: rewrote one relative import path "./chain-registry" -> "../chain/chain-registry" to match the vendored folder layout. No logic changed.
  // ─────────────────────────────────────────────────────────────────────────────

  /**
 * Contract Registry â€” single source of truth for every on-chain address.
 *
 * Every contract / wallet address the app references MUST appear here with
 * its role, status, chain, and a canonical explorer link generated by
 * chain-registry helpers. Do NOT duplicate address literals in components,
 * hooks, docs (outside DOCUMENTATION_AUTHORITY_MAP.md), or other libs.
 *
 * Status vocabulary:
 *   â€¢ LIVE     â€” deployed and integrated. Reads/writes safe per role.
 *   â€¢ DEPLOYED â€” on-chain but UI does not write to it yet.
 *   â€¢ PENDING  â€” not deployed. address MUST be null.
 *
 * Future contracts (e.g. SeatRecord721) MUST stay PENDING with address:null
 * until a real deployment tx hash is available. No placeholder strings,
 * no "0x000â€¦", no inferred addresses.
 */

import {
  CONTRACTS,
  isLiveAddress,
  MEMBERSHIP_SALE_V2_CONTRACT_ADDRESS,
  MEMBERSHIP_SALE_V3_CONTRACT_ADDRESS,
  SOURCE_REGISTRY_V1_CONTRACT_ADDRESS,
} from "./syndicate-config";
import { addressUrl, tokenUrl, contractUrl, CHAIN_REGISTRY } from "../chain/chain-registry";

export type ContractRole =
  | "token"          // ERC-20
  | "stablecoin"     // ERC-20 stablecoin (USDC)
  | "sale"           // Membership Sale contract
  | "source-registry" // V3 source policy registry
  | "commission-router" // future referral routing contract
  | "archive1155"    // SyndicateArchive1155
  | "seat-record-721"// future ERC-721
  | "lp-pair"        // Trader Joe LP pair
  | "wallet";        // public allocation wallet

export type ContractStatus = "LIVE" | "DEPLOYED" | "PENDING";

export type ContractEntry = {
  key: string;
  name: string;
  role: ContractRole;
  status: ContractStatus;
  /** Null when status is PENDING. */
  address: string | null;
  chainId: number;
  /** Canonical explorer link (token / address). Null when address is null. */
  explorerUrl: string | null;
  /** Where the ABI lives in source, when applicable. */
  abiSource?: string;
  /** Verification source link, when known. */
  verification?: string;
  /** One-line role description for docs / debug panels. */
  notes: string;
};

const chainId = CHAIN_REGISTRY.id;

function entry(
  key: string,
  name: string,
  role: ContractRole,
  status: ContractStatus,
  address: string | null,
  notes: string,
  abiSource?: string,
  verification?: string,
): ContractEntry {
  const explorerUrl =
    address && isLiveAddress(address)
      ? role === "token" || role === "stablecoin"
        ? tokenUrl(address)
        : role === "archive1155" || role === "sale" || role === "source-registry" || role === "seat-record-721"
          ? contractUrl(address)
          : addressUrl(address)
      : null;
  return {
    key, name, role, status, address, chainId, explorerUrl, abiSource, verification, notes,
  };
}

export const CONTRACT_REGISTRY: ContractEntry[] = [
  entry(
    "SYN_TOKEN",
    "SYN Token",
    "token",
    "LIVE",
    CONTRACTS.SYN_CONTRACT_ADDRESS,
    "ERC-20, fixed 1,000,000,000 supply, no admin, no mint, no tax.",
    undefined,
    "https://repo.sourcify.dev/43114/" + CONTRACTS.SYN_CONTRACT_ADDRESS,
  ),
  entry(
    "USDC",
    "USDC (Avalanche)",
    "stablecoin",
    "LIVE",
    CONTRACTS.USDC_CONTRACT_ADDRESS,
    "Native USDC on Avalanche C-Chain. Used for sale + Patron Seal mint.",
  ),
  entry(
    "MEMBERSHIP_SALE",
    "Syndicate Membership Sale",
    "sale",
    "LIVE",
    CONTRACTS.MEMBERSHIP_SALE_CONTRACT_ADDRESS,
    "USDC to SYN sale, 70/20/10 split enforced on-chain. SEALED / sale closed - on-chain paused with 0 inventory; kept for history and independent verification (status LIVE = contract verifiable, not currently selling). Active buy target is V3.",
    "src/lib/sale-abi.ts",
  ),
  entry(
    "MEMBERSHIP_SALE_V2",
    "Syndicate Membership Sale V2",
    "sale",
    "LIVE",
    MEMBERSHIP_SALE_V2_CONTRACT_ADDRESS,
    "Model 2 continuation sale (per-era SYN caps, V1 recognition; external CommissionRouter unset). PAUSED on-chain and retained as a historical scan source for member continuity and the recovery boundary. New frontend buys now target MembershipSaleV3.",
    "src/lib/sale-abi.ts",
  ),
  entry(
    "SOURCE_REGISTRY_V1",
    "SourceRegistryV1",
    "source-registry",
    "DEPLOYED",
    SOURCE_REGISTRY_V1_CONTRACT_ADDRESS,
    "V3 source policy registry. Deployed and owner-accepted with one validated internal source test now PAUSED; referral/source UI remains inactive.",
    "contracts/src/SourceRegistryV1.sol",
  ),
  entry(
    "MEMBERSHIP_SALE_V3",
    "MembershipSaleV3",
    "sale",
    "LIVE",
    MEMBERSHIP_SALE_V3_CONTRACT_ADDRESS,
    "Current frontend buy target. Funded with SYN and owner-accepted. Public buys use zero sourceId; referral/source/claim UI remains inactive.",
    "src/lib/sale-abi.ts",
  ),
  entry(
    "COMMISSION_ROUTER_V1",
    "CommissionRouterV1",
    "commission-router",
    "PENDING",
    null,
    "Production-candidate referral router exists in contracts/src/CommissionRouterV1.sol, but no router is deployed or wired live. Referral remains REQUIRES CONTRACT until a real address is verified.",
    "contracts/src/CommissionRouterV1.sol",
  ),
  entry(
    "ARCHIVE_1155",
    "SyndicateArchive1155",
    "archive1155",
    "LIVE",
    CONTRACTS.ARCHIVE_NFT_CONTRACT_ADDRESS,
    "Multi-ID artifact contract. ID 1 public mint is open; ID 3 Patron Seal is contract/read gated and only shown as mintable from live Archive1155 reads. See archive-id-registry.ts.",
    "src/lib/archive-nft-abi.ts",
  ),
  entry(
    "SEAT_RECORD_721",
    "SyndicateSeatRecord721",
    "seat-record-721",
    "PENDING",
    null,
    "Future ERC-721 identity record derived from SYN seat truth and the Holder Index. NOT DEPLOYED. Do not infer an address.",
  ),
  entry(
    "LP_PAIR",
    "Trader Joe v1 SYN/USDC Pair",
    "lp-pair",
    "LIVE",
    CONTRACTS.LP_PAIR_ADDRESS,
    "Live LP pool. Reserves + price read on-chain.",
  ),
  entry(
    "VAULT_WALLET",
    "Vault Wallet",
    "wallet",
    "LIVE",
    CONTRACTS.VAULT_WALLET,
    "Receives 70% of every USDC purchase.",
  ),
  entry(
    "LIQUIDITY_WALLET",
    "Liquidity Wallet",
    "wallet",
    "LIVE",
    CONTRACTS.LIQUIDITY_WALLET,
    "Receives 20% of every USDC purchase.",
  ),
  entry(
    "OPERATIONS_WALLET",
    "Operations Wallet",
    "wallet",
    "LIVE",
    CONTRACTS.OPERATIONS_WALLET,
    "Receives 10% of every USDC purchase.",
  ),
  entry(
    "FOUNDER_WALLET",
    "Founder Wallet",
    "wallet",
    "LIVE",
    "0x88EC79AF0d5A2F3b83022A1770c645506803Dd73",
    "Founder allocation wallet â€” public, vested.",
  ),
  entry(
    "MEMBERSHIP_SYN_WALLET",
    "Membership Distribution Wallet",
    "wallet",
    "LIVE",
    CONTRACTS.MEMBERSHIP_SYN_WALLET,
    "Holds SYN inventory for membership purchases.",
  ),
];

export function contractByKey(key: string): ContractEntry | undefined {
  return CONTRACT_REGISTRY.find((c) => c.key === key);
}

export function liveContracts(): ContractEntry[] {
  return CONTRACT_REGISTRY.filter((c) => c.status === "LIVE");
}

export function pendingContracts(): ContractEntry[] {
  return CONTRACT_REGISTRY.filter((c) => c.status === "PENDING");
}
