// SPDX-License-Identifier: MIT
// ⛔ TEST-ONLY — the bench, never deployed. Production = src/MeritDistributor.sol (binds the REAL Circle USDC at deploy). guard-prod-purity.sh enforces the separation.
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {MeritDistributor} from "../src/MeritDistributor.sol";
import {MockUSDC} from "./mocks/MockUSDC.sol";

/// @notice THE DIFFERENTIAL FIXTURE TEST (spec §1 — a hard gate). The committed
///         contracts/test/fixtures/merkle-fixture.json is generated by the PRODUCTION JS
///         builder (api-server season-merkle, OZ StandardMerkleTree) against the PINNED
///         (chainId 31337, pool 0x…A11CE) vector; this test deploys the REAL contract AT
///         that address and every JS proof must claim — the JS tooling and the .sol agree
///         BYTE-FOR-BYTE or this is red. Kills the origin's tooling/contract
///         encoding-mismatch class forever. Drift is guarded server-side too
///         (api-server season-merkle:guard regenerates + diffs the file).
contract MerkleFixtureTest is Test {
    address constant PINNED_POOL = 0x00000000000000000000000000000000000A11cE;

    MeritDistributor internal pool;
    MockUSDC internal usdc;
    address internal founder = makeAddr("founder");
    address internal executor = makeAddr("executor");

    bytes32 internal root;
    address[] internal accounts;
    uint256[] internal amounts;
    bytes32[][] internal proofs;
    uint256 internal roundId;
    uint256 internal budget;

    function setUp() public {
        string memory json = vm.readFile("test/fixtures/merkle-fixture.json");
        root = vm.parseJsonBytes32(json, ".root");
        accounts = vm.parseJsonAddressArray(json, ".accounts");
        amounts = vm.parseJsonUintArray(json, ".amounts");
        roundId = vm.parseJsonUint(json, ".roundId");
        budget = vm.parseJsonUint(json, ".budgetRaw");
        proofs = new bytes32[][](accounts.length);
        for (uint256 i; i < accounts.length; ++i) {
            proofs[i] = vm.parseJsonBytes32Array(json, string.concat(".proof", vm.toString(i)));
        }

        usdc = new MockUSDC();
        // The REAL contract, AT the pinned address the fixture was generated for.
        deployCodeTo(
            "MeritDistributor.sol:MeritDistributor",
            abi.encode(
                address(usdc), makeAddr("sealer"), executor, makeAddr("guardian"),
                uint64(72 hours), uint64(730 days), uint64(72 hours), uint64(7 days),
                uint64(14 days), keccak256("s1")
            ),
            PINNED_POOL
        );
        pool = MeritDistributor(PINNED_POOL);
        pool.transferOwnership(founder);
        vm.prank(founder);
        pool.acceptOwnership();

        usdc.mint(founder, uint256(budget));
        vm.startPrank(founder);
        usdc.approve(PINNED_POOL, type(uint256).max);
        pool.fund(uint128(budget), MeritDistributor.Bucket.COMMITTED, 1);
        vm.stopPrank();
        vm.prank(executor);
        pool.postRound(roundId, root, uint128(budget), "fixture", MeritDistributor.RoundClass.INTERIM);
        vm.warp(block.timestamp + 72 hours);
        pool.activate(roundId);
    }

    /// Every JS-generated proof claims on-chain — byte-for-byte agreement.
    function test_everyFixtureProofClaims() public {
        for (uint256 i; i < accounts.length; ++i) {
            assertTrue(
                pool.verifyClaim(roundId, accounts[i], amounts[i], proofs[i]),
                "JS proof rejected by the contract: encoding drift"
            );
            pool.claimFor(roundId, accounts[i], amounts[i], proofs[i]);
            assertEq(usdc.balanceOf(accounts[i]), amounts[i]);
        }
        assertEq(pool.totalPaid(), uint128(budget), "the fixture round pays its budget exactly");
        assertTrue(pool.conservationHolds());
    }

    /// The same fixture data with a wrong amount is rejected — agreement is not laxity.
    function test_fixtureWrongAmountRejected() public {
        assertFalse(pool.verifyClaim(roundId, accounts[0], amounts[0] + 1, proofs[0]));
        vm.expectRevert(MeritDistributor.BadProof.selector);
        pool.claimFor(roundId, accounts[0], amounts[0] + 1, proofs[0]);
    }
}
