import { Router, type IRouter } from "express";
import { GetHolderIndexResponse } from "@workspace/api-zod";
import { HOLDER_INDEX_SNAPSHOT } from "../lib/protocol/holderIndexSnapshot";

/**
 * Aggregate-only Holder Index — served from the STATIC hash-pinned snapshot
 * generated by the founder-gated holder-index:build (freezeGate pattern: no
 * runtime database read; the offline reconciler keeps the snapshot honest and
 * fails closed on any divergence). Aggregate counts and era boundaries only;
 * no per-seat rows, no directory, no member-identifying data.
 */

const MODE = "READ_ONLY_HOLDER_INDEX_AGGREGATES" as const;

/** Boundary-aware output gate: a standalone 0x 40-hex token is an address. */
const STANDALONE_ADDRESS_RE = /0x[0-9a-fA-F]{40}(?![0-9a-fA-F])/;

const payload = { mode: MODE, ...HOLDER_INDEX_SNAPSHOT };
const serialized = JSON.stringify(payload);
if (STANDALONE_ADDRESS_RE.test(serialized)) {
  throw new Error(
    "SAFETY VIOLATION: a standalone 0x address token was detected in the holder-index payload; refusing to serve.",
  );
}
const holderIndexResponse = GetHolderIndexResponse.parse(payload);

const router: IRouter = Router();

router.get("/holder-index", (_req, res) => {
  res.json(holderIndexResponse);
});

export default router;
