/**
 * Holder Index static snapshot (SERVED, aggregate-only) — GENERATED FILE.
 * ---------------------------------------------------------------------------
 * DO NOT EDIT BY HAND. Generated by the founder-gated holder-index:build
 * script from the VERIFIED continuity build (freezeGate pattern).
 *
 * Served code imports this constant and performs NO runtime database read.
 * The scripts-side reconciler (holder-index:reconcile) re-derives this exact
 * object from the database and FAILS CLOSED (non-zero exit) on any mismatch,
 * stale hash, era-boundary violation, or missing timestamp truth — on such a
 * failure this file must be regenerated through the gated build, never
 * hand-patched.
 *
 * PRIVACY BOUNDARY: aggregate counts and era boundaries only. No wallet
 * addresses, no per-seat rows, no memberNumber-to-wallet linkage, no
 * directory. Entry-level member data remains SERVER-ONLY PII with no public
 * UI/API/projection.
 */

export interface HolderIndexSnapshotEra {
  readonly era: "PART_B_FREEZE_ROOT" | "V3_EMITTED";
  readonly label: string;
  readonly doctrine: string;
  readonly count: number;
  readonly seatNumberLow: number;
  readonly seatNumberHigh: number;
}

export interface HolderIndexSnapshot {
  readonly gate: "HOLDER_INDEX_AGGREGATES_V1";
  readonly status: "VERIFIED";
  readonly chainId: number;
  readonly freezeBlock: number;
  readonly memberTotal: number;
  readonly eras: readonly HolderIndexSnapshotEra[];
  readonly timestampCoverage: {
    readonly withVerifiedTimestamp: number;
    readonly total: number;
  };
  readonly provenance: {
    readonly runId: number;
    readonly builtAt: string;
    readonly builderVersion: string;
    readonly sourceDeterminismHash: string;
    readonly inputSaleEventCount: number;
    readonly inputMaxSaleEventRawId: number | null;
  };
  readonly boundaries: readonly string[];
  readonly snapshotHash: string;
}

export const HOLDER_INDEX_SNAPSHOT: HolderIndexSnapshot = {
  "gate": "HOLDER_INDEX_AGGREGATES_V1",
  "status": "VERIFIED",
  "chainId": 43114,
  "freezeBlock": 88496414,
  "memberTotal": 14,
  "eras": [
    {
      "era": "PART_B_FREEZE_ROOT",
      "label": "historical freeze / on-chain root",
      "doctrine": "Seats #1–#8: authority is the verified historical freeze + on-chain V1_MEMBER_ROOT. Imported once from the verified canonical artifact, never re-derived or renumbered; memberNumber 0 remains a sentinel, never a seat.",
      "count": 8,
      "seatNumberLow": 1,
      "seatNumberHigh": 8
    },
    {
      "era": "V3_EMITTED",
      "label": "V3 engine event",
      "doctrine": "Seats #9+: authority is the memberNumber emitted by V3 engine events on-chain. Read from raw indexed events, never inferred, never renumbered.",
      "count": 6,
      "seatNumberLow": 9,
      "seatNumberHigh": 14
    }
  ],
  "timestampCoverage": {
    "withVerifiedTimestamp": 14,
    "total": 14
  },
  "provenance": {
    "runId": 5,
    "builtAt": "2026-07-16T15:26:53.673Z",
    "builderVersion": "member-continuity-builder/1.1.0-s3b",
    "sourceDeterminismHash": "sha256:439192b47e63a44e21ab59f3cce54fe7be34d6c9af557100ead4d2983ee42249",
    "inputSaleEventCount": 35,
    "inputMaxSaleEventRawId": 41
  },
  "boundaries": [
    "Aggregate counts only: no wallet addresses, no per-seat public roster, no memberNumber-to-wallet linkage, no directory.",
    "Served code imports this static snapshot and performs NO runtime database read (freezeGate pattern); the scripts-side reconciler re-derives it from the database and fails closed on any mismatch.",
    "Era provenance is always labelled: historical freeze / on-chain root (#1–#8) vs V3 engine event (#9+). The two authorities are never collapsed into one undifferentiated sequence.",
    "Membership recognition only — no financial framing, no economic projection. Member self-readback is session-bound OWN-ROW only (founder Decision 5a): a signed wallet may resolve its own standing against this snapshot; no public directory, roster, or arbitrary lookup exists."
  ],
  "snapshotHash": "sha256:65acf2f15c3e336d0bb79ef884cdfbb3446f283d071c94c8c252e56b2d717dc4"
} as const;
