/**
 * Introduction read-model snapshot (SERVED) — GENERATED FILE. DO NOT EDIT.
 * Generated by the founder-gated introductions:build script (R5) from a
 * COMPLETE zero-gap scan of MembershipPurchasedV3 + live durable/escrow reads.
 * Address-free by construction: no wallet, no member number, no tx hash, no
 * raw sourceId — per-source rows are keyed by the opaque sourceKey
 * (introductionReadmodel.sourceKeyOf). Honest as of `asOfBlock`.
 */

import type { IntroductionReadmodel } from "./introductionReadmodel";

export interface IntroductionSnapshot {
  readonly status: "VERIFIED";
  readonly model: IntroductionReadmodel;
  readonly snapshotHash: string;
  readonly provenance: {
    readonly builtAt: string;
    readonly builderVersion: string;
    readonly rpcCallCount: number;
  };
}

export const INTRODUCTION_SNAPSHOT: IntroductionSnapshot = {
  "status": "VERIFIED",
  "model": {
    "gate": "INTRODUCTION_READMODEL_V1",
    "chainId": 43114,
    "saleKey": "MEMBERSHIP_SALE_V3",
    "fromBlock": 88505301,
    "asOfBlock": 90187222,
    "durableTest": "SYN_BALANCE_HELD",
    "totals": {
      "attributedPurchases": 3,
      "distinctSources": 2,
      "introducedMembers": 3,
      "durableIntroductions": 3,
      "commissionPaidRaw": "750000"
    },
    "bySource": {
      "src_36101e67d77b151bd9b04938": {
        "attributedPurchases": 2,
        "introducedMembers": 2,
        "durableIntroductions": 2,
        "commissionPaidRaw": "500000",
        "escrowOwedRaw": "0",
        "firstBlock": 88806161,
        "lastBlock": 90160483,
        "currentBps": 500,
        "entitledBps": 500,
        "entitledTitle": "Emerging",
        "promotionDue": false,
        "crossedAtBlock": null,
        "crossedAtDateUtc": null
      },
      "src_ea47feba757c852a42c68dbb": {
        "attributedPurchases": 1,
        "introducedMembers": 1,
        "durableIntroductions": 1,
        "commissionPaidRaw": "250000",
        "escrowOwedRaw": "0",
        "firstBlock": 90187059,
        "lastBlock": 90187059,
        "currentBps": 500,
        "entitledBps": 500,
        "entitledTitle": "Emerging",
        "promotionDue": false,
        "crossedAtBlock": null,
        "crossedAtDateUtc": null
      }
    }
  },
  "snapshotHash": "sha256:a5409ac3cb27d2e5fc75484a1cdfa4fc20934c4de98d52524b1d080ce57aa2ca",
  "provenance": {
    "builtAt": "2026-07-13T07:17:27.139Z",
    "builderVersion": "introduction-readmodel v1 (R5, July 2026)",
    "rpcCallCount": 12
  }
};
