/**
 * Introduction read-model snapshot (SERVED) — GENERATED FILE. DO NOT EDIT.
 * Generated by the founder-gated introductions:build script (R5) from a
 * COMPLETE zero-gap scan of MembershipPurchasedV3 + live durable/escrow reads.
 * Address-free by construction: no wallet, no member number, no tx hash, no
 * raw sourceId — per-source rows are keyed by the opaque sourceKey
 * (introductionReadmodel.sourceKeyOf). Honest as of `asOfBlock`.
 */

import type { IntroductionReadmodel } from "./introductionReadmodel";

export interface IntroductionSnapshot {
  readonly status: "VERIFIED";
  readonly model: IntroductionReadmodel;
  readonly snapshotHash: string;
  readonly provenance: {
    readonly builtAt: string;
    readonly builderVersion: string;
    readonly rpcCallCount: number;
  };
}

export const INTRODUCTION_SNAPSHOT: IntroductionSnapshot = {
  "status": "VERIFIED",
  "model": {
    "gate": "INTRODUCTION_READMODEL_V1",
    "chainId": 43114,
    "saleKey": "MEMBERSHIP_SALE_V3",
    "fromBlock": 88505301,
    "asOfBlock": 90184731,
    "durableTest": "SYN_BALANCE_HELD",
    "totals": {
      "attributedPurchases": 2,
      "distinctSources": 1,
      "introducedMembers": 2,
      "durableIntroductions": 2,
      "commissionPaidRaw": "500000"
    },
    "bySource": {
      "src_36101e67d77b151bd9b04938": {
        "attributedPurchases": 2,
        "introducedMembers": 2,
        "durableIntroductions": 2,
        "commissionPaidRaw": "500000",
        "escrowOwedRaw": "0",
        "firstBlock": 88806161,
        "lastBlock": 90160483,
        "currentBps": 500,
        "entitledBps": 500,
        "entitledTitle": "Emerging",
        "promotionDue": false,
        "crossedAtBlock": null,
        "crossedAtDateUtc": null
      }
    }
  },
  "snapshotHash": "sha256:5a3c9df95a6d69d8281ac4c40cc882ed1b9e8168a0e32736d02ca188c65c3e99",
  "provenance": {
    "builtAt": "2026-07-13T06:34:07.548Z",
    "builderVersion": "introduction-readmodel v1 (R5, July 2026)",
    "rpcCallCount": 8
  }
};
