/**
 * Introduction read-model snapshot (SERVED) — GENERATED FILE. DO NOT EDIT.
 * Generated by the founder-gated introductions:build script (R5) from a
 * COMPLETE zero-gap scan of MembershipPurchasedV3 + live durable/escrow reads.
 * Address-free by construction: no wallet, no member number, no tx hash, no
 * raw sourceId — per-source rows are keyed by the opaque sourceKey
 * (introductionReadmodel.sourceKeyOf). Honest as of `asOfBlock`.
 */

import type { IntroductionReadmodel } from "./introductionReadmodel";

export interface IntroductionSnapshot {
  readonly status: "VERIFIED";
  readonly model: IntroductionReadmodel;
  readonly snapshotHash: string;
  readonly provenance: {
    readonly builtAt: string;
    readonly builderVersion: string;
    readonly rpcCallCount: number;
  };
}

export const INTRODUCTION_SNAPSHOT: IntroductionSnapshot = {
  "status": "VERIFIED",
  "model": {
    "gate": "INTRODUCTION_READMODEL_V1",
    "chainId": 43114,
    "saleKey": "MEMBERSHIP_SALE_V3",
    "fromBlock": 88505301,
    "asOfBlock": 90180944,
    "durableTest": "SYN_BALANCE_HELD",
    "totals": {
      "attributedPurchases": 2,
      "distinctSources": 1,
      "introducedMembers": 2,
      "durableIntroductions": 2,
      "commissionPaidRaw": "500000"
    },
    "bySource": {
      "src_36101e67d77b151bd9b04938": {
        "attributedPurchases": 2,
        "introducedMembers": 2,
        "durableIntroductions": 2,
        "commissionPaidRaw": "500000",
        "escrowOwedRaw": "0",
        "firstBlock": 88806161,
        "lastBlock": 90160483
      }
    }
  },
  "snapshotHash": "sha256:f6de0e2ef9bcec6516d5bc55d57963065022a98224f18ea7f209f501fb9192c6",
  "provenance": {
    "builtAt": "2026-07-13T05:27:58.016Z",
    "builderVersion": "introduction-readmodel v1 (R5, July 2026)",
    "rpcCallCount": 4
  }
};
