/**
 * Referral attribution activity snapshot (SERVED, aggregates-only) — GENERATED FILE.
 * ---------------------------------------------------------------------------
 * DO NOT EDIT BY HAND. Generated by the founder-gated referral-attribution:build
 * script from a chunked read-only eth_getLogs scan of the SourceRegistryV1
 * lifecycle events (freezeGate / holder-index pattern). The RPC provider caps
 * eth_getLogs at a 10,000-block range, so this count CANNOT be a per-request
 * live read; it is a chain-derived INDEXED count, honest as of `asOfBlock`.
 *
 * Served code imports this constant and performs NO runtime scan or DB read.
 *
 * PRIVACY / HONESTY BOUNDARY: aggregate event counts only. No wallet
 * addresses, no source ids, no topics, no transaction hashes. The count is an
 * ACTIVITY COUNT — never a USDC or commission figure. No commission has ever
 * been paid on-chain; CommissionRouterV1 is not deployed.
 */

export interface ReferralAttributionSnapshot {
  readonly gate: "REFERRAL_ATTRIBUTION_ACTIVITY_V1";
  readonly status: "VERIFIED";
  readonly chainId: number;
  readonly registryKey: "SOURCE_REGISTRY_V1";
  readonly fromBlock: number;
  readonly asOfBlock: number;
  readonly totalEvents: number;
  readonly byEvent: {
    readonly SourceCreated: number;
    readonly SourceTermsUpdated: number;
    readonly SourceStatusChanged: number;
    readonly SourceWalletUpdated: number;
    readonly SourcePayoutWalletUpdated: number;
  };
  readonly otherEventCount: number;
  readonly doctrine: string;
  readonly provenance: {
    readonly builtAt: string;
    readonly builderVersion: string;
    readonly rpcCallCount: number;
  };
  readonly snapshotHash: string;
}

export const REFERRAL_ATTRIBUTION_SNAPSHOT: ReferralAttributionSnapshot = {
  "gate": "REFERRAL_ATTRIBUTION_ACTIVITY_V1",
  "status": "VERIFIED",
  "chainId": 43114,
  "registryKey": "SOURCE_REGISTRY_V1",
  "fromBlock": 87157852,
  "asOfBlock": 89832255,
  "totalEvents": 10,
  "byEvent": {
    "SourceCreated": 1,
    "SourceTermsUpdated": 2,
    "SourceStatusChanged": 4,
    "SourceWalletUpdated": 0,
    "SourcePayoutWalletUpdated": 0
  },
  "otherEventCount": 3,
  "doctrine": "Attribution ACTIVITY COUNT only (registry lifecycle events) — never a USDC or commission figure. No commission has ever been paid on-chain; CommissionRouterV1 is not deployed.",
  "provenance": {
    "builtAt": "2026-07-08T23:32:02.198Z",
    "builderVersion": "referral-attribution-build v1 (reconciliation slice, July 2026)",
    "rpcCallCount": 270
  },
  "snapshotHash": "sha256:7b388ee1fce9922c619b6adb7e601a88a65e109c313991e372a60fd7a0a9ddff"
};
