/**
 * season-merkle-fixture — emits THE DIFFERENTIAL FIXTURE (spec §1, two-phase).
 * ---------------------------------------------------------------------------
 * Phase 1 (CI, this file): a PINNED vector — chainId 31337 + a fixed pool
 * address — generated by the SAME production builder (`buildPayoutRoot`) the
 * real rounds will use, written into contracts/test/fixtures/ where the
 * Foundry `MerkleFixture.t.sol` deploys the REAL contract AT that address
 * (deployCodeTo) and must accept every proof: the JS tooling and the .sol
 * agree BYTE-FOR-BYTE or the build is red — the origin's tooling/contract
 * encoding-mismatch class, dead forever.
 * Phase 2 (activation runbook): re-run against the LIVE mainnet address and
 * re-verify before the first real root.
 *
 * Run: pnpm run season-merkle:fixture   (drift-checked by season-merkle:guard)
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildPayoutRoot } from "../src/season/merkle.js";

export const FIXTURE_CHAIN_ID = 31337n; // forge's default
export const FIXTURE_POOL = "0x00000000000000000000000000000000000A11cE" as const;
export const FIXTURE_ROUND_ID = 1001;
export const FIXTURE_LEAVES = [
  { account: "0x1111111111111111111111111111111111111111", amountRaw: 400_000_000n },
  { account: "0x2222222222222222222222222222222222222222", amountRaw: 250_000_000n },
  { account: "0x3333333333333333333333333333333333333333", amountRaw: 150_000_000n },
  { account: "0x4444444444444444444444444444444444444444", amountRaw: 120_000_000n },
  { account: "0x5555555555555555555555555555555555555555", amountRaw: 80_000_000n },
] as const;
export const FIXTURE_BUDGET = 1_000_000_000n; // 1,000 USDC — Σ leaves exactly

export function generateFixtureJson(): string {
  const tree = buildPayoutRoot({
    chainId: FIXTURE_CHAIN_ID,
    pool: FIXTURE_POOL,
    roundId: FIXTURE_ROUND_ID,
    budgetRaw: FIXTURE_BUDGET,
    leaves: FIXTURE_LEAVES.map((l) => ({ account: l.account, amountRaw: l.amountRaw })),
  });
  const obj: Record<string, unknown> = {
    format: "merkle-differential-fixture@1",
    chainId: FIXTURE_CHAIN_ID.toString(),
    pool: FIXTURE_POOL,
    roundId: FIXTURE_ROUND_ID,
    budgetRaw: FIXTURE_BUDGET.toString(),
    root: tree.root,
    accounts: FIXTURE_LEAVES.map((l) => l.account),
    amounts: FIXTURE_LEAVES.map((l) => l.amountRaw.toString()),
  };
  FIXTURE_LEAVES.forEach((l, i) => {
    obj[`proof${i}`] = tree.proofs.get(l.account);
  });
  return JSON.stringify(obj, null, 2) + "\n";
}

const isMain = process.argv[1]?.replace(/\\/g, "/").endsWith("season-merkle-fixture.ts");
if (isMain) {
  const outDir = resolve(import.meta.dirname, "../../../contracts/test/fixtures");
  mkdirSync(outDir, { recursive: true });
  const json = generateFixtureJson();
  writeFileSync(resolve(outDir, "merkle-fixture.json"), json);
  console.log(`fixture written: contracts/test/fixtures/merkle-fixture.json`);
}
