import React from "react";
import { Link } from "wouter";
import {
  useGetSourceStatus,
  useGetHolderIndex,
  type SourceStatusItem,
} from "@workspace/api-client-react";
import { DataStatusNote } from "@/components/DataStatusNote";
import { PostureBadge } from "@/components/PostureBadge";
import { PublicPage } from "@/components/PublicPage";
import { SurfaceMapSection } from "@/components/SurfaceMapSection";
import { Card } from "@/components/ui/card";
import { Spinner } from "@/components/ui/spinner";
import { AlertTriangle } from "lucide-react";
import { CONTENT_LINK_CLS } from "@/lib/contentLink";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

function shortHash(hash: string): string {
  return hash.length > 28 ? `${hash.slice(0, 18)}…${hash.slice(-8)}` : hash;
}

function HolderIndexSection() {
  const { data, isLoading, isError } = useGetHolderIndex();
  const verified = data?.status === "VERIFIED";

  return (
    <section className="mb-12">
      <div className="mb-4">
        <h2 className="type-h2 text-foreground">Holder Index</h2>
        <p className="text-muted-foreground text-sm mt-1 measure">
          Aggregate-only membership continuity index served from a static, hash-pinned snapshot
          generated by a founder-gated offline build from the VERIFIED member-continuity build —
          served code performs no runtime database read, and an offline reconciler fails closed on
          any divergence. Counts and era boundaries only: no per-seat roster, no directory, no
          member-identifying data. Every aggregate carries its numbering-era provenance.
        </p>
      </div>

      {isLoading && (
        <Card className="bg-card/40 border-border/50 p-10">
          <div className="flex flex-col items-center justify-center gap-3 text-muted-foreground">
            <Spinner className="h-6 w-6 text-primary" />
            <p className="text-sm">Loading holder index snapshot…</p>
          </div>
        </Card>
      )}

      {(isError || (data && !verified)) && (
        <Card className="bg-card/40 border-border/50 p-8">
          <div className="flex items-start gap-3">
            <div className="p-1.5 bg-warning/10 rounded-md text-warning shrink-0 mt-0.5">
              <AlertTriangle className="h-4 w-4" />
            </div>
            <div>
              <h4 className="text-sm font-medium text-foreground">Holder index unavailable</h4>
              <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
                The verified snapshot could not be read. No fallback, cached, or placeholder
                counts are shown — this surface only renders the hash-pinned VERIFIED snapshot
                from the holder-index endpoint.
              </p>
            </div>
          </div>
        </Card>
      )}

      {data && verified && (
        <Card className="bg-card/40 border-border/50 p-6">
          <div className="flex flex-wrap items-baseline justify-between gap-4">
            <div>
              <div className="type-eyebrow text-muted-foreground">
                Recognized members
              </div>
              <div className="text-4xl font-light text-foreground mt-1">{data.memberTotal}</div>
            </div>
            <div className="flex flex-wrap items-center gap-2">
              <span className="type-caption px-2 py-0.5 rounded border border-success/30 bg-success/10 text-success">
                {data.status}
              </span>
              <span className="type-caption px-2 py-0.5 rounded border border-border/60 bg-muted/30 text-muted-foreground">
                {data.mode}
              </span>
            </div>
          </div>

          <div className="mt-6 auto-grid gap-3">
            {data.eras.map((era) => (
              <div key={era.era} className="rounded-lg border border-border/50 bg-background/40 p-4">
                <div className="flex items-center justify-between gap-3">
                  <span className="type-caption px-2 py-0.5 rounded border border-primary/30 bg-primary/10 text-primary whitespace-nowrap">
                    {era.label}
                  </span>
                  <span className="font-mono text-xs text-muted-foreground whitespace-nowrap">
                    seats #{era.seatNumberLow}–#{era.seatNumberHigh}
                  </span>
                </div>
                <div className="text-2xl font-light text-foreground mt-3">{era.count}</div>
                <p className="text-xs text-muted-foreground mt-2 leading-relaxed">{era.doctrine}</p>
              </div>
            ))}
          </div>

          <div className="mt-5 flex flex-wrap items-center gap-x-4 gap-y-1 type-caption text-muted-foreground border-t border-border/40 pt-4">
            <span>
              Chain <span className="text-foreground/80">{data.chainId}</span>
            </span>
            <span className="text-border">·</span>
            <span>
              Freeze block <span className="text-foreground/80">{data.freezeBlock}</span>
            </span>
            <span className="text-border">·</span>
            <span>
              Chain-verified entry timestamps{" "}
              <span className="text-foreground/80">
                {data.timestampCoverage.withVerifiedTimestamp}/{data.timestampCoverage.total}
              </span>
            </span>
            <span className="text-border">·</span>
            <span>
              Build <span className="text-foreground/80">{data.provenance.builderVersion}</span>
            </span>
            <span className="text-border">·</span>
            <span>
              Built{" "}
              <span className="text-foreground/80">
                {new Date(data.provenance.builtAt).toISOString().slice(0, 10)}
              </span>
            </span>
            <span className="text-border">·</span>
            <span>
              Snapshot <span className="text-foreground/80">{shortHash(data.snapshotHash)}</span>
            </span>
          </div>
        </Card>
      )}
    </section>
  );
}

export default function SystemStatus() {
  const { data, isLoading, isError } = useGetSourceStatus();

  const items: SourceStatusItem[] = data ? Object.values(data.categories) : [];

  // THE ONE-JOB SPLIT + THE SHELL (founder "construis 1-5", 2026-07-30).
  // ① /status was the one footer door off the PublicPage shell — raw div, a
  //    decorative icon glued to the h1. It now opens like every sibling.
  // ② The full Protocol-reality tables LEFT this page: /map is the live
  //    reality read, /status is the POSTURE ledger + holder index + surface
  //    map — two doors, one job each, never five duplicate tables (the audit's
  //    twin-tables finding). One pointer line keeps the path.
  // ③ WORK-FIRST: the ~90-word section intro died with the section; the page
  //    opens directly on the ledger its title promises.
  return (
    <PublicPage
      eyebrow="Public proof"
      title="System Status"
      lead="The honesty hub: what is live versus pending — the posture of every source, the holder index, and the surface map. The live figures themselves are read on the Protocol Map."
      variant="app"
    >
      <h2 className="type-h2 text-foreground mb-2">Source-status registry</h2>
      {/* THE SENTENCE DESCRIBED A COLUMN THAT NO LONGER EXISTS (2026-07-26).
          Removing the all-`null` Value column left this note explaining why
          "every value here is null by design" — a description of an absence the
          reader can no longer see, which is worse than the column was. It now
          says what the table IS rather than what it lacks.
          And `null` left the copy: it is developer vocabulary on a public page,
          and the human words say the same thing better. */}
      <DataStatusNote description="Source-status registry — separate from the live protocol reality read above. It records the POSTURE of each source: what it is, where it comes from, and how far it may be trusted. It performs no chain reads and holds no balances, no member data and no RPC, so it carries no figures at all — a verified static canon reference, never a live read." />

      {data && (
        <div className="mb-6 flex flex-wrap items-center gap-x-4 gap-y-1 font-mono text-xs text-muted-foreground">
          <span>
            Mode <span className="text-foreground/80">{data.mode}</span>
          </span>
          <span className="text-border">·</span>
          <span>
            Source <span className="text-foreground/80">{data.generatedBy}</span>
          </span>
          <span className="text-border">·</span>
          <span>
            Expected chain <span className="text-foreground/80">{data.expectedChainId}</span>
          </span>
          <span className="text-border">·</span>
          <span>
            As of <span className="text-foreground/80">{new Date(data.asOf).toISOString().slice(0, 10)}</span>
          </span>
          <span className="text-border">·</span>
          <span className="text-foreground/80">{items.length} categories</span>
        </div>
      )}

      {isLoading && (
        <Card className="bg-card/40 border-border/50 p-12">
          <div className="flex flex-col items-center justify-center gap-3 text-muted-foreground">
            <Spinner className="h-6 w-6 text-primary" />
            <p className="text-sm">Loading source posture…</p>
          </div>
        </Card>
      )}

      {isError && (
        <Card className="bg-card/40 border-border/50 p-8">
          <div className="flex items-start gap-3">
            <div className="p-1.5 bg-warning/10 rounded-md text-warning shrink-0 mt-0.5">
              <AlertTriangle className="h-4 w-4" />
            </div>
            <div>
              <h4 className="text-sm font-medium text-foreground">Source registry unavailable</h4>
              <p className="text-sm text-muted-foreground mt-1 leading-relaxed">
                The posture registry could not be reached. No fallback or placeholder values are
                shown — this surface only renders verified posture data from the source-status
                endpoint.
              </p>
            </div>
          </div>
        </Card>
      )}

      {data && (
        <Card className="bg-card/40 border-border/50 overflow-hidden">
          <Table>
            <TableHeader className="bg-muted/30">
              <TableRow className="border-border/30">
                <TableHead className="w-[230px] font-medium text-foreground">Category</TableHead>
                <TableHead className="font-medium text-foreground">Note</TableHead>
                <TableHead className="w-[200px] font-medium text-foreground">Class</TableHead>
                <TableHead className="text-right font-medium text-foreground">Posture</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {items.map((item) => (
                <TableRow key={item.key} className="border-border/30 hover:bg-muted/10 transition-colors align-top">
                  <TableCell className="font-medium text-foreground/90">
                    <div>{item.label}</div>
                    <div className="type-caption text-muted-foreground mt-1">{item.sourceRef}</div>
                  </TableCell>
                  <TableCell className="text-muted-foreground text-sm">
                    <div className="leading-relaxed">{item.note}</div>
                    <div className="type-caption text-muted-foreground mt-1">
                      Surface · {item.surface}
                    </div>
                  </TableCell>
                  <TableCell className="text-sm">
                    <div className="type-caption text-foreground/70">{item.publicClass}</div>
                    <div className="text-xs text-muted-foreground mt-1 capitalize">
                      Confidence · {item.confidence}
                    </div>
                  </TableCell>
                  {/* THE "VALUE" COLUMN IS GONE (first-visit review, 2026-07-26).
                      It printed the literal string `null` on EVERY row, with
                      "posture-only" underneath — a whole column whose only content
                      was the announcement that it has no content. To a visitor who
                      does not read code, `null` down a public status page reads as
                      something broken; to one who does, it reads as a debug view
                      shipped by accident. Either way it costs trust on the page
                      whose entire job is being trustworthy.
                      WORK-FIRST §3 is explicit: if information serves nobody on
                      that page, it is not shown at all. The posture badge already
                      says everything this column was standing in for. */}
                  <TableCell className="text-right">
                    <PostureBadge posture={item.posture} />
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </Card>
      )}

      <div className="mt-12">
        <HolderIndexSection />
      </div>

      <div className="mt-12">
        <h2 className="type-h2 text-foreground mb-2">Surface map</h2>
        <p className="text-muted-foreground text-sm mb-6 measure">
          Every surface in the foundation, its audience, and its honest lifecycle — projected
          from the surface-classification registry, not a hand-maintained list.
        </p>
        {/* AUD-TRUTH-2 (founder Ruling ②, 2026-07-16): PUBLIC-SEES-ADMIN-NEVER —
            the operator/admin surface map MOVED to the operator side (/os-map,
            build-gated); the public page projects PUBLIC + MEMBER only. One
            shared component — the map can never fork into two truths. */}
        <SurfaceMapSection audiences={["PUBLIC", "MEMBER_PREVIEW"]} />
      </div>

      <p className="mt-12 text-sm text-muted-foreground border-t border-border/40 pt-4">
        Looking for the live chain reads themselves — contract presence, token
        metadata, the sale engine's figures, the archive state? They have one
        home: the <Link href="/map" className={CONTENT_LINK_CLS}>Protocol Map</Link>.
      </p>
    </PublicPage>
  );
}
